name = "QBSolvers"
uuid = "5d646e68-7e02-4d4b-9db2-54f9f7ce8ddd"
authors = ["Xun-Jian Li <xunjianli@g.ucla.edu>", "Seyoon Ko <kos@ucla.edu>", "Alfonso Landeros <alandero@ucr.edu>", "Hua Zhou <hzhou@ucla.edu>", "Kenneth Lange <klange@ucla.edu>"]
version = "0.1.0"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BangBang = "0.4.4"
Printf = "1.11.0"
SparseArrays = "1.11.0"
